name: 'cobra_etl'
version: '1.0.0'
config-version: 2

profile: 'cobra_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  cobra_etl:
    staging:
      +materialized: view
      +schema: cobra_staging
    mart:
      +materialized: incremental
      +schema: public
